### ISSUE TITLE
Allow install cert by pfx file only

### ISSUE THREAD

**Issue by mikes-gh** [rmbolger/Posh-ACME.Deploy#13]
All the deploy scripts have a mandatory Thumbprint parameter.  It might be nice to be able to deploy a cert given a PfxFile only.

**Comment by rmbolger** [comment]
I like this idea. I just have to figure out how to finagle the parameter sets to support the concept while not breaking the ability to pipe the certificate objects into them from Posh-ACME.

**Comment by mikes-gh** [comment]
I guess you leave all the parameters as they are but require one of thumbprint or pfx.  If no thumbprint is supplied then pfx is mandatory.  Add logic to get thumbprint if only pfx is supplied But I'm no expert in powershell parameters.  Its probably not that easy :-)

**Comment by mikes-gh** [comment]
I am not sure you ever need both thumbprint and pfx?

**Comment by rmbolger** [comment]
I haven't actually tested it, but I fear splitting up Thumbprint and the File parameters into two distinct sets would end up confusing the parameter binder when an object that has all of them (like the PACertificate object) was piped in.

Again, I'm pretty sure this will be doable. I just have to futz with things.

**Comment by rmbolger** [comment]
Added in 1.4.0
