### ISSUE TITLE
Guide for Exchange

### ISSUE THREAD

**Issue by legolass73** [rmbolger/Posh-ACME.Deploy#18]
Hello, would it be possible to have some kind of guide to install a certificate with Posh-Acme and Posh-Acme.Deploy on an Exchange server? Like for example some command line that would allow us to do it ourselves?

**Comment by rmbolger** [comment]
Unfortunately, I have zero experience using Exchange and would be a terrible candidate to create such a guide. The `Set-ExchangeCertificate` function was contributed by a user. But the function's documentation (`Get-Help Set-ExchangeCertificate`) looks pretty straightforward. The only Exchange specific parameter is `ExchangeServices` which appears to be the list of services to configure.

On the Posh-ACME side of things, there's plenty of documentation on the documentation site. I'd probably start with the tutorial and work on getting the cert first without worrying about deploying it to Exchange.

https://poshac.me/docs/v4/Tutorial/

Then once you're comfortable with the process of obtaining the cert, work in the Set-ExchangeCertificate function to deploy it to your server.

**Comment by legolass73** [comment]
hello, I looked at the file to try to understand how it works, but I do not really understand how to put the parameters like the service exchange, should we put them like the parameters of the addons of the dnschallenge ?

**Comment by rmbolger** [comment]
Here's the documentation for [Enable-ExchangeCertificate](https://docs.microsoft.com/en-us/powershell/module/exchange/enable-exchangecertificate) which is what the `Set-ExchangeCertificate` function is using under the hood. The `ExchangeServices` parameter is being passed directly to the `Services` parameter in that function. The examples all use a comma delimited string based on the Exchange services you have enabled. So it might look something like this:

```powershell
$cert | Set-ExchangeCertificate -ExchangeServices 'POP,IMAP,SMTP,IIS'
```

**Comment by markpizz** [comment]
> a comma delimited string based on the Exchange services you have enabled.

You don't have to restrict it to just the services you've enabled.  No harm exists if you always specify 'POP,IMAP,SMTP,IIS' but then don't actually enable POP or IMAP.

The Set-ExchangeCertificate script was probably most intended to help with deployment of renewal certificates,  I would recommend that you use the Exchange Admin Center web interface to initially install your certificate and then leverage Set-ExchangeCertificate as you update your certificates before they expire.
