### ISSUE TITLE
Support for newer Powershell core versions 

### ISSUE THREAD

**Issue by stevenh-ACM** [rmbolger/Posh-ACME.Deploy#20]
webadministration is not available in Powershell 7.x but iisadministration is.

Please fix set-iiscertificate so it doesn't require webadministration on windows 10.

**Comment by rmbolger** [comment]
Hi @stevenh-ACM, you're in luck! There's a `Set-IISCertificateNew` function that I totally forgot to mention in the 1.3.0 release notes that already uses the IISAdministration module and should work on PowerShell 7+. The caveat is that you need the latest 1.1.0.0 version of the module from PSGallery instead of the version that comes with Windows. Specifically, it's using some of the new *-IISSiteBinding functions that don't exist in the 1.0 version. More information on it is here:

https://blogs.iis.net/iisteam/introducing-iisadministration-in-the-powershell-gallery

**Comment by stevenh-ACM** [comment]
Ryan, Get-PACertificate | Set-IISCertificateNew doesn't seem to work?

**Comment by stevenh-ACM** [comment]
BTW - it does in powershell 5.1 but not on powershell 7.2.1. With 7.2.1 the following is experienced:
get-pacertificate | set-iiscertificatenew -sitename 'Default Web Site' -port 443 -verbose
VERBOSE: IIS site binding already exists for *:443:
changed port:
get-pacertificate | set-iiscertificatenew -sitename 'Default Web Site' -port 8443 -verbose
VERBOSE: Adding IIS site binding for *:8443:
Set-IISCertificateNew: Filename: \\?\C:\WINDOWS\system32\inetsrv\config\applicationHost.config
Error: Cannot commit configuration changes because the file has changed on disk
nothing was added. then re-run the last line again:
VERBOSE: IIS site binding already exists for *:8443: ??

Thoughts?? Thanks!

**Comment by stevenh-ACM** [comment]
BTW there's nothing the the ~/inetsrv/config folder. It won't even open with FileExplorer.

**Comment by rmbolger** [comment]
Is your PowerShell session elevated (running as admin)? I'm pretty sure you can't change site binding stuff as a non-admin user and that might show up as weird errors with the module. I'll see if I can reproduce it on my end though.

**Comment by rmbolger** [comment]
I haven't been able to reproduce that error on a Win 10 machine I spun up running PowerShell 7.2.1. But after reviewing the code, I'm pretty sure the main thing that is failing is the function's attempt to remove the old binding before adding the new one. The IISAdministration module doesn't really support the concept of changing an existing binding (like updating the cert thumbprint). You can only remove and re-add with new details.

So the code that tries to remove the old binding fails....and apparently I don't have good enough error checking there, so it moves on to the code that tries to re-add it but thinks it already exists. I can't say for sure why the removal is failing though.

If you want to just get things working. I'd probably try manually removing any existing HTTPS bindings from the site. Then run the command again and see if it works.

You can also take a look at the current bindings as they exist from IISAdministration's perspective like this:

```powershell
Import-Module IISAdministration -UseWindowsPowerShell
Get-IISSiteBinding 'Default Web Site' -Protocol https
```

You could then even try removing a binding like this:

```powershell
Remove-IISSiteBinding 'Default Web Site' -BindingInformation '*:443:' -Protocol https -RemoveConfigOnly
```

**Comment by inzi** [comment]
My two cents - Set Set-IISCertificate is not working for me either.

Server 2019
pwsh ver 7

I was able to manually install the PFX.

My commands looks a little different:


`
  $cert = New-PACertificate $certNames -AcceptTOS -Contact $email -Plugin Namecheap -PluginArgs $pArgs -FriendlyName $fiendlyName -Name $domainName -Verbose # -Install
    $cert | Set-IISCertificate -SiteName $url -Debug  #-RemoveOldCert <- only on renewal or it deletes servers self signed cert 
`

I'll try changing it to a chain, but this was working on another server under ps 5.

I'll debug more later.

**Comment by rmbolger** [comment]
Hi @inzi. Where you using `Set-IISCertificate` or `Set-IISCertificateNew`?

Only the "New" version will work in PS7+ but also requires that you have the `IISAdministration` module version 1.1.0.0 or later installed. The non-New version relies on the `WebAdministration` module which does not work in PS7.

**Comment by inzi** [comment]
I will try it now. Thanks for that info.
