### ISSUE TITLE
Allow for multiple policies and/or wildcards with Set-NPSCertificate

### ISSUE THREAD

**Issue by sevmonster** [rmbolger/Posh-ACME.Deploy#24]
It seems trivial enough to modify the XPath selector to support either wildcard strings or search for multiple policies. In our environment we have a lot of policies and it is much easier to select all of them (since they all use the same cert). As of right now I am just getting all policies using similar code to what is already in `Set-NPSCertificate` and running each through it.

```powershell
$cert = Submit-Renewal oursite.tld
if ($cert) {
    # https://github.com/rmbolger/Posh-ACME.Deploy/blob/main/Posh-ACME.Deploy/Public/Set-NPSCertificate.ps1
    ([xml](Get-Content ([Environment]::ExpandEnvironmentVariables('%SystemRoot%\System32\ias\ias.xml')))).SelectSingleNode("//RadiusProfiles//*").ChildNodes.name | % {
        Set-NPSCertificate $cert.Thumbprint -PolicyName $_ -RemoveOldCert
    }
}
```

**Comment by rmbolger** [comment]
Hey @sevmonster. Thanks for reaching out. I didn't write the original implementation and I'm not really familiar with NPS, but I think I understand what you're asking for.

Do you think having an alternative parameter like `-PolicyXPath` that would set the cert on everything that matched would be usable by others? Or should it be something like changing PolicyName to allow standard string matching wildcards. So like:

```powershell
    # set on policies starting with "Corp"
    $cert | Set-NPSCertificate -PolicyName 'Corp*'

    # set on all policies
    $cert | Set-NPSCertificate -PolicyName '*'
```

Also, might you have a sample `ias.xml` file I could use to test against?

**Comment by rmbolger** [comment]
Got the redacted sample ias.xml. Thanks. I'll try to get to this soon. Things are a bit hectic with end of the year stuff right now though.

**Comment by rmbolger** [comment]
Thanks again for the sample ias.xml. It was super helpful. I have a test version pushed to the main branch now that has a `-PolicyXPath` parameter added to it. The expression I was using with it against your sample file looked like this:

```powershell
$cert | Set-NPSCertificate -PolicyXPath '//RadiusProfiles//Children//*[descendant::msEAPConfiguration]'
```

Technically, it works without the "descendant" portion of the XPath and just ignores the elements that don't have a config to update. But it seemed more efficient to be specific.

**Comment by sevmonster** [comment]
Looks good, tested and works in our environment. Thanks a bunch. I see no problems pushing this.

**Comment by rmbolger** [comment]
Excellent. I'll try to get an updated release out soon.

**Comment by rmbolger** [comment]
Live in 1.6.0
