### ISSUE TITLE
Installing cert on IIS -> getting error: A specified logon session does not exist. It may already have been terminated

### ISSUE THREAD

**Issue by Coleman0701** [rmbolger/Posh-ACME.Deploy#25]
Hello @rmbolger,
it is me again :), I asked a question the other day related to Posh.Acme project.. 

I've been successfully issuing certificates using our ACME server implementation with Posh-ACME client. 
Now I am trying to install certs to IIS with Posh-ACME.Deploy. I am getting this error. 

`PS C:\WINDOWS\system32>> New-PACertificate -Domain acme.sec.cezd.corp -CertKeyLength 2048 -Subject 'CN=acme' -Install -force -verbose  | Set-IISCertificate -SiteName 'acme' -Verbose -Port 443 -Debug -HostHeader acme.sec.cezd.corp -RequireSNI
VERBOSE: Updating directory info from https://acme.sec.cezd.corp/acme-server
VERBOSE: Using ACME Server https://acme.sec.cezd.corp/acme-server
VERBOSE: Using account TestovaciUcet
VERBOSE: Order name not specified, using 'acme.sec.cezd.corp'
VERBOSE: Creating a new order 'acme.sec.cezd.corp' for acme.sec.cezd.corp
VERBOSE: Removing old private key
VERBOSE: Finalizing the order.
VERBOSE: Creating new certificate request with key length 2048.
VERBOSE: Creating new private key for the certificate request.
VERBOSE: Downloading signed certificate
VERBOSE: Updating cert expiration and renewal window
VERBOSE: Successfully created certificate.
VERBOSE: Importing CN=acme certificate to LocalMachine\My.
VERBOSE: Adding chain cert 'CN=acme' with thumbprint BC43FC2E50C9DEA43A3650C4C3E6EED9CBF74356 to LocalMachine\CA store.
VERBOSE: IIS Binding already exists for *:443:acme.sec.cezd.corp
VERBOSE: Checking SSL binding !443!acme.sec.cezd.corp
VERBOSE: Removing old thumbprint from !443!acme.sec.cezd.corp SSL binding
VERBOSE: Adding certificate thumbprint BC43FC2E50C9DEA43A3650C4C3E6EED9CBF74356
WARNING: Binding host name 'acme.sec.cezd.corp' is not equals to certificate subject name 'acme'. Client may not be able to connect to the site using HTTPS protocol.

Confirm
A specified logon session does not exist. It may already have been terminated
[Y] Yes  [A] Yes to All  [H] Halt Command  [S] Suspend  [?] Help (default is "Y"): y
Set-IISCertificate : A specified logon session does not exist. It may already have been terminated
At line:1 char:113 ..
. -verbose  | Set-IISCertificate -SiteName 'acme' -Verbose -Port 443 -D ...
                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
     CategoryInfo          : NotSpecified: (:) [Set-IISCertificate], Win32Exception
     FullyQualifiedErrorId : System.ComponentModel.Win32Exception,Set-IISCertificate`

Actually, I get this error even if I try to do it manually. Select issued cert in IIS bindings console. 

![image](https://github.com/rmbolger/Posh-ACME.Deploy/assets/102318043/bd040bbd-1bc8-4035-9572-2cf5f773e55a)

I should have proper rights to do so. 
I am able to select other certs and configure binding with certs I issued in the past (not using Posh Acme)

Please, do you have any idea what can be wrong? 

Thank you a lot for your time and response.

**Comment by rmbolger** [comment]
Hey @Coleman0701. Unforunately, I haven't seen that error before. The only uncommon thing about your setup is that you appear to be using an internal ACME CA as noted by the `.corp` TLD and use of the `-Subject` parameter. *(Out of curiosity, why mess with the subject? Would `-FriendlyName` be more appropriate?)*

Does the cert show up normally in the `certlm.msc` snap-in with the little key icon indicating it has a private key associated with it? Are the other certs that work also from the same CA? What Windows version is this?

What I'd probably try next is re-configuring the binding to a cert that works so the site is functional again. Delete the ACME cert from the Windows cert store. Force renew the ACME cert so you get a new copy, but don't try the deploy function yet. Just try modifying the site binding manually.

If that doesn't work, I might try deleting everything again. Then changing the order properties so it doesn't self-install the cert. Force renew again. Manually import the cert PFX and manually try the binding again.

**Comment by Coleman0701** [comment]
Hey @rmbolger , 
I'll try your hints and get back you you. 

Would it be possible to arrange a conf call with you? I would want to describe you the concept of our ACME server implementation. I do like your Posh-Acme client and I'd want to be recommeding it to our clients.

**Comment by rmbolger** [comment]
I didn't mean to imply there's anything wrong with using an internal ACME CA. I think that's super cool. It's just not the typical use case so it could plausibly have something to do with your problem.

I don't think I'm up for a 1:1 right now. But you can hit me up via DM on the [PowerShell Discord Server](https://discord.gg/Ju25cw6). I'm also `rmbolger` there.

**Comment by Coleman0701** [comment]
Hello @rmbolger 
Everything's OK now. Our server responded with PEM including only the issued cert. Not including the whole chain. This was done by purpose in order to test the main flow. 
We've included the whole chain in the PEM response and it is OK now. 

Cert used to show up normally in certlm.msc even before but I guess it was somehow corrupted and that is why I couldn't select the cert for IIS site binding.

**Comment by Coleman0701** [comment]
![image](https://github.com/rmbolger/Posh-ACME.Deploy/assets/102318043/4a4f55ef-eb0d-47f2-937d-ab5e9a5b9a60)

**Comment by Coleman0701** [comment]
I've already tested our server with many different clients. I dare to say we've successfully implemeted internal ACME Server / CA.

**Comment by rmbolger** [comment]
That's awesome. Congrats!
