### ISSUE TITLE
TypeNotFound Microsoft.Web.Administration.SslFlags:TypeName

### ISSUE THREAD

**Issue by fubar-coder** [rmbolger/Posh-ACME.Deploy#31]
# Description

I get a "TypeNotFound" error when I try to deploy the certificate. The deployment itself seems to work, but the error message was scaring me 😉 .

# Details

```text
Der Typ [Microsoft.Web.Administration.SslFlags] wurde nicht gefunden.
In C:\Program Files\WindowsPowerShell\Modules\Posh-ACME.Deploy\2.0.0\Public\Set-IISCertificate.ps1:49 Zeichen:28
+ ...           'RequireSNI' = [Microsoft.Web.Administration.SslFlags]::Sni
+                              ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (Microsoft.Web.Administration.SslFlags:TypeName) [], RuntimeException
    + FullyQualifiedErrorId : TypeNotFound
```

# Info

- Windows Server 2019
- PowerShell 5.1

**Comment by rmbolger** [comment]
Hi @fubar-coder, thanks for reaching out. That .NET enum is supposed to be exposed by the underlying IISAdministration module which first made me think you might have forgotten to install it. However, Set-IISCertificate should have already confirmed the module is installed before it gets to that line of code.

After messing around a bit on a test system, I think I confirmed what's going on. It looks like the Enum is not actually available to the PowerShell environment until one of the IISAdministration functions is actually called. Can you do me a favor and give this a try from a fresh/empty PowerShell session on that server? Don't import any modules first, just open a new session and run these commands.

```powershell
[Microsoft.Web.Administration.SslFlags].GetEnumNames()
Get-IISSite
[Microsoft.Web.Administration.SslFlags].GetEnumNames()
```

If I'm right, the first call to `GetEnumNames()` should fail. But the last one should succeed.

As a tangent, I also noticed that even when the enum is found, it has different values on different supported OSes which means there's a separate bug in the code that I need to fix for old Windows versions like 2019.

**Comment by fubar-coder** [comment]
@rmbolger I executed the statements, and it's exactly as you expected. The first statement failed, but the third works.

**Comment by rmbolger** [comment]
I pushed a fix to the main branch that seems to be working for me. I'd be grateful if you could test it out before I push a bugfix release.

**Comment by fubar-coder** [comment]
@rmbolger Thanks, I tested it and it works as expected 👍

**Comment by jpmoock** [comment]
Can this change be pushed to the Powershell Gallery please?

**Comment by rmbolger** [comment]
Oh man, I'm so sorry. This totally fell off my radar when the issue was closed. Not your fault. I usually keep them open to remind me to post an update and close when I actually push a release. v2.0.1 is up in the gallery now.
