### ISSUE TITLE
Dev install module path

### ISSUE THREAD

**Issue by mikes-gh** [rmbolger/Posh-ACME.Deploy#7]
https://github.com/rmbolger/Posh-ACME.Deploy/blob/4ab7e35a9df0baa3eb5113d99a279e01044c1229/instdev.ps1#L5

On My Machine

`$env:psmodulePath` 

doesnt contain the above as my ~~home~~ documents directory is on a server.

Please see

https://github.com/PowerShell/PowerShellGet/pull/179/commits/6ed796f7d0fd772cb8ad1e13e9461fc05564c459

If you want the same behaviour as PowerShellGet.

**Comment by rmbolger** [comment]
Just for clarification. Your entire home directory is on a server, or just the Documents folder?

**Comment by mikes-gh** [comment]
Just documents.
If you follow the same logic as PowerShellGet for install location it will work.
Currently if I use your dev install script and do a subsequent import it cannot find the module as per the powershell commit explanation.
Shouldn't break existing just fix the scenario where documents is not in the local user path.

Regards

Mike Surcouf
+44 1534 836355

________________________________

**Comment by mikes-gh** [comment]
If you decide to make the change the bug would also be in 
https://github.com/rmbolger/Posh-ACME/blob/master/instdev.ps1

**Comment by rmbolger** [comment]
Yeah, this is something I'd want to fix on all my modules.

**Comment by rmbolger** [comment]
I think this should be fixed for you now. Let me know and I'll update it everywhere else as well.

**Comment by mikes-gh** [comment]
Yes tested and now works for me thank you
